### ISSUE TITLE
Jenkins doesn't stop after timeout

### ISSUE THREAD

**Issue by Garfield96** [AutoPas/AutoPas#200]
**Describe the bug**
Jenkins is waiting forever if a test runs out of time. Although it recognizes an exception it doesn't stop the build process.

**To Reproduce**
Steps to reproduce the behaviour:
Check out Jenkins Build #15 (03.05.2019 23:37:31) of branch linked-cell-smaller-cell-sizes.

**Expected behaviour**
Stop build pipeline after timeout.

**Output**
```
java.net.SocketTimeoutException: sent ping but didn't receive pong within 30000ms (after 480 successful ping/pongs)

	at okhttp3.internal.ws.RealWebSocket.writePingFrame(RealWebSocket.java:546)

	at okhttp3.internal.ws.RealWebSocket$PingRunnable.run(RealWebSocket.java:530)

	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)

	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)

	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

	at java.lang.Thread.run(Thread.java:745)
```

**Build environment**
 - Jenkins

**Comment by SteffenSeckler** [comment]
true, fyi: you have a deadlock in
Generated/TraversalTest.testTraversaltest7x8x9_overlap3/sliced_N3off
to reproduce (if compiled with openmp enabled):
OMP_NUM_THREADS=2 ctest -R Generated/TraversalTest.testTraversaltest7x8x9_overlap3/sliced_N3off

**Comment by Garfield96** [comment]
Thank you. I'll check the deadlock problem.
Nevertheless, if a deadlock, endless loop, ... occure Jenkins should stop the build process after some time. Maybe we can set the timeout parameter (https://jenkins.io/doc/pipeline/steps/workflow-basic-steps/#timeout-enforce-time-limit) to ensure that. I think 2 h should be enough even with CUDA enabled.

**Comment by SteffenSeckler** [comment]
added a timeout in efe41d38ffeccce3174762386311b032155c0da2
