### ISSUE TITLE
missing SoALoader and SoAExtractor in FlopCounter

### ISSUE THREAD

**Issue by SteffenSeckler** [AutoPas/AutoPas#53]
**Describe the bug**
The FlopCounter does not implement the SoALoader/SoAExctractor functions.
Executing iteratePairwiseSoA with the FlopCounter will lead to:
```
terminate called after throwing an instance of 'autopas::utils::ExceptionHandler::AutoPasException'
  what():  Functor::SoALoader: not yet implemented
```
**To Reproduce**
1. build AutoPas normally
2. execute e.g. `md-flexible --container linked --cutoff 1. --data-layout soa --functor lj --iterations 10 --particles-per-dimension 10 --particle-spacing 0.4`
3. See error

**Expected behavior**
FlopCounter sshould implement the SoALoader and SoAExtractor, where the latter is empty

**gdb-trace**
```
Starting program: 

Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) where
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff6cb9801 in __GI_abort () at abort.c:79
#2  0x00007ffff76ac8fb in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff76b2d3a in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff76b2d95 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff76b2fe8 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x000000000049326a in autopas::utils::ExceptionHandler::exception<autopas::utils::ExceptionHandler::AutoPasException> (e=...)
    at ../../src/utils/ExceptionHandler.h:58
#7  0x000000000049295b in autopas::utils::ExceptionHandler::exception<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >
    (exceptionString=<incomplete type>) at ../../src/utils/ExceptionHandler.cpp:17
#8  0x00000000004929f0 in autopas::utils::ExceptionHandler::exception<char const*> (exceptionString=0x496b61 "Functor::SoALoader: not yet implemented")
    at ../../src/utils/ExceptionHandler.cpp:22
#9  0x000000000047357a in autopas::Functor<PrintableMolecule, autopas::FullParticleCell<PrintableMolecule> >::SoALoader (this=0x7fffffffdbb0, cell=..., 
    soa=..., offset=0) at ../../src/./pairwiseFunctors/Functor.h:111
#10 0x00000000004897be in autopas::LinkedCells<PrintableMolecule, autopas::FullParticleCell<PrintableMolecule> >::loadSoAs<autopas::Functor<PrintableMolecule, autopas::FullParticleCell<PrintableMolecule> > > (this=0x6c94b0, functor=0x7fffffffdbb0) at ../../src/./containers/LinkedCells.h:218
#11 0x00000000004893f2 in autopas::LinkedCells<PrintableMolecule, autopas::FullParticleCell<PrintableMolecule> >::iteratePairwiseSoA2<autopas::Functor<PrintableMolecule, autopas::FullParticleCell<PrintableMolecule> > > (this=0x6c94b0, f=0x7fffffffdbb0, useNewton3=true)
    at ../../src/./containers/LinkedCells.h:128
#12 0x000000000047ff8c in autopas::LinkedCells<PrintableMolecule, autopas::FullParticleCell<PrintableMolecule> >::iteratePairwiseSoA (this=0x6c94b0, 
    f=0x7fffffffdbb0, useNewton3=true) at ../../src/./containers/LinkedCells.h:116
#13 0x0000000000470c73 in AutoPas<PrintableMolecule, autopas::FullParticleCell<PrintableMolecule> >::iteratePairwise (this=0x7fffffffdc48, 
    f=0x7fffffffdbb0, dataLayoutOption=autopas::soa) at ../../src/./AutoPas.h:138
#14 0x000000000046f4f8 in main (argc=15, argv=0x7fffffffddc8) at ../../examples/md-flexible/main.cpp:100
```

**Additional context**
Please also add a unit test for that

**Comment by SteffenSeckler** [comment]
@FG-TUM @tchipev for one of you ;)

**Comment by SteffenSeckler** [comment]
@FG-TUM you probably want to fix this, as I just broke the trunk by merging #55 which actually checks the examples ;)

**Comment by SteffenSeckler** [comment]
(mistakenly closed)

**Comment by tchipev** [comment]
> @FG-TUM @tchipev for one of you ;)
I don't know git.
